### PR TITLE
Add a "reveal votes" button

### PR DESCRIPTION
**Pull request by rocketmo**
This PR adds in a "reveal votes" button, shown within planning poker rooms. Pressing on the button will reveal all votes, even if not all participants have submitted their votes.

One pain point our team has had is when not everyone in the room has voted, but the team still wanted to reveal the votes. For example, when someone steps away from their machine before submitting a vote, the rest of the group has to wait until they return and vote before the votes can be shown. This button gives the option to reveal all votes whenever the room is ready for them to be revealed, regardless of the status of the current votes.

https://user-images.githubusercontent.com/25872132/208321891-df3b0d3f-47b6-44e2-9042-3ead3fc0f983.mp4

### CODE REVIEW

**Comment by rocketmo** [comment]
Hey @booc0mtaco, it's been a while! Hope this is an okay change to make, it'd make the sprint planning meetings on team Klondike a little smoother 😄

**Comment by booc0mtaco** [comment]
@rocketmo Yo! This seems like a reasonable feature, so nice work. I will likely not get to this until next week (I can merge now but can't deploy until I return home), but a few checks I'll mention:

* ideally, `isRevealed` should also change to `true` when `allVoted` becomes true (that way there is only one path for cards to be shown with or without votes). does it work like that?
* instead of a button, I would want to (eventually) make it a checkbox that is clickable IFF `allVoted` is false (when `allVoted` becomes true, it checks this, AND disables that checkbox until reset)

As you can tell, this is mostly to make sure the state has a single source of truth for which side of the cards are showing.

**Comment by rocketmo** [comment]
Thanks for the suggestions @booc0mtaco! I've gone ahead and made it so that when `allVoted` changes to true, we also change `isRevealed` to true. It removed the need to check if either is true in a few locations.

I've also updated the "Reveal Votes" button so that it disables when `isRevealed` is true. Since, `isRevealed` changes to true when `allVoted` changes to true, the button should also be disabled when `allVoted` is true.

I'll leave changing the button to a checkbox to you 😄 . I did make some small adjustments to the css since there currently aren't any styles for disabled buttons. Hope that's okay - here's what the disabled button looks like (left button is enabled, right button is disabled).
Screen Shot 2022-12-19 at 7 01 10 PM

**Comment by booc0mtaco** [comment]
@rocketmo I'll approve and merge this in. As I'm off til next week, I may spend a little more time on this. If yall have any curious feature requests lemme know. 

Keep an eye open for a deploy of the new functionality later this week. Thanks for the contrib :)

**Review by booc0mtaco — APPROVED** [review]

**Comment by rocketmo** [comment]
Sweet, thanks Andrew!

**Comment by booc0mtaco** [comment]
@rocketmo deployed to site. I noticed an interesting behavior: 

## when the number of members in a channel changes after the votes have been revealed, the "reveal vote" button goes out of sync.

Steps to reproduce:

*  log in to new room
* cast a vote
* note that the "reveal votes" button has disabled
* have another user join the room

Expected result: 

* all users will see the same state of the reveal button
* cards on other user's screens revert back to hidden (now that all voted is false again)

Instead, it will reveal all cards on the existing users' screens, but for the new user they would have to click the reveal button to see what others done. This is actually nice, since the new person joining could still vote without seeing what other people did already. I like this behavior :)

**Pull request merged**
